apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-next-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ericdrosas87/iac-tutorial.git
    targetRevision: main
    path: deploy/chart

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
